### ISSUE TITLE
Number "1" output after caption

### ISSUE THREAD

**Issue by wuuti** [degoya/degoyaActionButton#1]
In 1.0.0-beta8 the caption of the button is suffixed by a "1" - perhaps a debug message?

![screenshot from 2015-10-02 15 20 30](https://cloud.githubusercontent.com/assets/2852461/10247404/241ac98e-6919-11e5-87b6-2554a2b253b1.png)

**Comment by wuuti** [comment]
Update: the "1" is only output if "Save resource" is set to "Yes".

**Comment by degoya** [comment]
was used for debuging. fixed with beta9.
