### ISSUE TITLE
Feature: make dialog boxes optional

### ISSUE THREAD

**Issue by wuuti** [degoya/degoyaActionButton#3]
Currently, as of 1.0.0-beta8, the following dialogs should be optional:
- Execute Action?
- Save not implemented
- Snippet output / snippet error

Not all actions are so heavy that you have to ask for confirmation in advance.
The TV options should provide ways to make the dialog pop ups optional.

**Comment by degoya** [comment]
the options have been added in beta9 for execute action and result (success & error) messages. The Save not implemented has been removed after the first version of save resource has been implemented with beta9 aswell.
