### ISSUE TITLE
Resource params in run snippet

### ISSUE THREAD

**Issue by faitno** [degoya/degoyaActionButton#6]
May I take resource params on running snippet?

for examle:

```
echo $resource->id;
echo $resource->pagetitle;
return 'success';
```

And over?

**Comment by degoya** [comment]
$resource is not set in your snippet.

try to set it with before you use it

<code>$resource = $modx->getObject('modResource', $resourceid);
</code>

but your echo break the return success. 
for testing better write to the error log

<code>$modx->log(modX::LOG_LEVEL_ERROR,'Pagetile of Resource: '.$resource->pagetitle); </code>

It is planed to have a snippet result with the success msg in a future version. 
check issue https://github.com/degoya/degoyaActionButton/issues/5

**Comment by faitno** [comment]
How do I know which resource launched a snippet?

**Comment by degoya** [comment]
$resourceid holds the id of the resource that triggered the snippet call

**Comment by faitno** [comment]
Very thanks!
